apiVersion: v1
kind: Service
metadata:
  name: project5
spec:
  selector:
    app: project5
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project5
  labels:
    app: project5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project5
  template:
    metadata:
      labels:
        app: project5
    spec:
      containers:
      - name: project5
        image: udacitycourseqwert/project5:latest
        imagePullPolicy: Always
        ports:
          - name: project5
            containerPort: 8080